2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_setup.py:_flush():69] setting env: {}
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_init.py:_log_setup():336] Logging user logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_090951-pp9yf7z4/logs/debug.log
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_init.py:_log_setup():337] Logging internal logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_090951-pp9yf7z4/logs/debug-internal.log
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_init.py:init():369] calling init triggers
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-24 09:09:51,811 INFO    MainThread:19677 [wandb_init.py:init():418] starting backend
2021-04-24 09:09:51,811 INFO    MainThread:19677 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-24 09:09:51,822 INFO    MainThread:19677 [backend.py:ensure_launched():123] starting backend process...
2021-04-24 09:09:51,830 INFO    MainThread:19677 [backend.py:ensure_launched():128] started backend process with pid: 19710
2021-04-24 09:09:51,831 INFO    MainThread:19677 [wandb_init.py:init():423] backend started and connected
2021-04-24 09:09:51,832 INFO    MainThread:19677 [wandb_init.py:init():465] updated telemetry
2021-04-24 09:09:51,833 INFO    MainThread:19677 [wandb_init.py:init():484] communicating current version
2021-04-24 09:09:52,380 INFO    MainThread:19677 [wandb_init.py:init():489] got version response 
2021-04-24 09:09:52,380 INFO    MainThread:19677 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-24 09:09:52,441 INFO    MainThread:19677 [wandb_init.py:init():522] starting run threads in backend
2021-04-24 09:09:56,145 INFO    MainThread:19677 [wandb_run.py:_console_start():1524] atexit reg
2021-04-24 09:09:56,146 INFO    MainThread:19677 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-24 09:09:56,146 INFO    MainThread:19677 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-24 09:09:56,148 INFO    MainThread:19677 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-24 09:09:56,148 INFO    MainThread:19677 [wandb_init.py:init():546] run started, returning control to user process
2021-04-24 09:09:59,402 INFO    MainThread:19677 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 1
2021-04-24 09:09:59,402 INFO    MainThread:19677 [wandb_run.py:_restore():1466] restore
2021-04-24 09:10:01,456 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:10:01,562 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:10:02,447 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 15976
}

2021-04-24 09:10:02,583 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15976
  total_bytes: 15976
}

2021-04-24 09:10:02,685 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15976
  total_bytes: 15976
}

2021-04-24 09:10:02,787 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15976
  total_bytes: 15976
}

2021-04-24 09:10:02,888 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15976
  total_bytes: 15976
}

2021-04-24 09:10:02,990 INFO    MainThread:19677 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15976
  total_bytes: 15976
}

2021-04-24 09:10:04,059 INFO    MainThread:19677 [wandb_run.py:_show_files():1838] logging synced files
