2021-04-24 09:44:20,948 INFO    MainThread:10511 [wandb_setup.py:_flush():69] setting env: {}
2021-04-24 09:44:20,948 INFO    MainThread:10511 [wandb_setup.py:_flush():69] setting login settings: {}
2021-04-24 09:44:20,948 INFO    MainThread:10511 [wandb_init.py:_log_setup():336] Logging user logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094420-2m3pk3jb/logs/debug.log
2021-04-24 09:44:20,949 INFO    MainThread:10511 [wandb_init.py:_log_setup():337] Logging internal logs to /home/arora/kaggle/shopee/src/wandb/run-20210424_094420-2m3pk3jb/logs/debug-internal.log
2021-04-24 09:44:20,949 INFO    MainThread:10511 [wandb_init.py:init():369] calling init triggers
2021-04-24 09:44:20,949 INFO    MainThread:10511 [wandb_init.py:init():376] wandb.init called with sweep_config: {}
config: {}
2021-04-24 09:44:20,949 INFO    MainThread:10511 [wandb_init.py:init():418] starting backend
2021-04-24 09:44:20,949 INFO    MainThread:10511 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-04-24 09:44:20,959 INFO    MainThread:10511 [backend.py:ensure_launched():123] starting backend process...
2021-04-24 09:44:20,967 INFO    MainThread:10511 [backend.py:ensure_launched():128] started backend process with pid: 10562
2021-04-24 09:44:20,968 INFO    MainThread:10511 [wandb_init.py:init():423] backend started and connected
2021-04-24 09:44:20,969 INFO    MainThread:10511 [wandb_init.py:init():465] updated telemetry
2021-04-24 09:44:20,970 INFO    MainThread:10511 [wandb_init.py:init():484] communicating current version
2021-04-24 09:44:21,512 INFO    MainThread:10511 [wandb_init.py:init():489] got version response 
2021-04-24 09:44:21,512 INFO    MainThread:10511 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-04-24 09:44:21,575 INFO    MainThread:10511 [wandb_init.py:init():522] starting run threads in backend
2021-04-24 09:44:25,189 INFO    MainThread:10511 [wandb_run.py:_console_start():1524] atexit reg
2021-04-24 09:44:25,189 INFO    MainThread:10511 [wandb_run.py:_redirect():1371] redirect: SettingsConsole.REDIRECT
2021-04-24 09:44:25,190 INFO    MainThread:10511 [wandb_run.py:_redirect():1376] Redirecting console.
2021-04-24 09:44:25,192 INFO    MainThread:10511 [wandb_run.py:_redirect():1438] Redirects installed.
2021-04-24 09:44:25,192 INFO    MainThread:10511 [wandb_init.py:init():546] run started, returning control to user process
2021-04-24 09:44:33,500 INFO    MainThread:10511 [wandb_run.py:_atexit_cleanup():1494] got exitcode: 255
2021-04-24 09:44:33,501 INFO    MainThread:10511 [wandb_run.py:_restore():1466] restore
2021-04-24 09:44:35,548 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:44:35,732 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 546
}

2021-04-24 09:44:36,587 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 546
  total_bytes: 15958
}

2021-04-24 09:44:36,688 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15958
  total_bytes: 15958
}

2021-04-24 09:44:36,790 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15958
  total_bytes: 15958
}

2021-04-24 09:44:36,891 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15958
  total_bytes: 15958
}

2021-04-24 09:44:36,993 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15958
  total_bytes: 15958
}

2021-04-24 09:44:37,095 INFO    MainThread:10511 [wandb_run.py:_wait_for_finish():1616] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15958
  total_bytes: 15958
}

2021-04-24 09:44:38,163 INFO    MainThread:10511 [wandb_run.py:_show_files():1838] logging synced files
